services:
  etl-app:
    container_name: rh_cramer_etl
    image: rh_cramer_etl:latest
    build: .
    restart: on-failure:3
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
      - STAGING_DIR=/app/staging
    volumes:
      - ./logs:/app/logs
      - ./staging:/app/staging
