version: '3.8'

services:
  etl-app:
    container_name: etl_rrhh_bot
    build: .
    restart: on-failure
    env_file:
      - .env
    
    environment:
      # VARIABLES PARA LA CONVERSIÓN
      - PFX_PASSWORD=${PFX_PASSWORD} 
      - CERT_THUMBPRINT=${CERT_THUMBPRINT}     
      
    volumes:
      - ./certs:/certs
      
      - ./logs:/app/logs